primary:
    datasource:
        url: jdbc:mysql://localhost:3306/flywaydemo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: username
        password: password
        driverClassName: com.mysql.jdbc.Driver
        max-wait: 10000
        max-active: 50
        test-on-borrow: true
        schemas: [flywaydemo]
       
       
